import { execSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outputFile = path.join(__dirname, '../src/generated/build-info.ts');

function run(cmd) {
    try {
        return execSync(cmd, { encoding: 'utf8', cwd: path.join(__dirname, '..') }).trim();
    } catch {
        return '';
    }
}

function getBuildUser() {
    return (
        process.env.BUILD_USER ||
        process.env.USER ||
        process.env.USERNAME ||
        process.env.LOGNAME ||
        os.userInfo().username ||
        ''
    );
}

function isCi() {
    const ciEnvVars = [
        'CI',
        'CONTINUOUS_INTEGRATION',
        'BUILD_NUMBER',
        'JENKINS_URL',
        'GITLAB_CI',
        'GITHUB_ACTIONS',
        'TRAVIS',
        'CIRCLECI',
        'APPVEYOR',
        'TEAMCITY_VERSION',
        'BUILDKITE',
        'DRONE',
        'CODEBUILD_BUILD_ID',
    ];

    return ciEnvVars.some((key) => Boolean(process.env[key]));
}

function formatBeijingTime(date) {
    const pad = (n) => String(n).padStart(2, '0');
    const d = new Date(date.getTime() + 8 * 60 * 60 * 1000);
    return (
        `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())} ` +
        `${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())}`
    );
}

const buildInfo = {
    buildTime: formatBeijingTime(new Date()),
    timestamp: new Date().getTime(),
    buildUser: getBuildUser(),
    hostname: os.hostname(),
    platform: os.platform(),
    arch: os.arch(),
    osRelease: os.release(),
    nodeVersion: process.version,
    npmVersion: run('npm --version'),
    ci: isCi(),
    ciName: process.env.CI_NAME || '',
};

const content = `// Auto-generated by scripts/build-info.js — do not edit manually
export const BUILD_INFO = ${JSON.stringify(buildInfo, null, 4)} as const;
`;

fs.writeFileSync(outputFile, content, 'utf8');
console.log(`✅ Generated build info: ${buildInfo.buildTime} → ${outputFile}`);
